### ISSUE TITLE
Function names: Swagger vs Resource Docs

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/API-Tester#4]
@simonredfern Iirc, you told me the API Tester should look at Swagger JSON (e.g. https://apisandbox.openbankproject.com/obp/v1.4.0/resource-docs/v3.0.0/swagger?core=&psd2=&obwg=). But i cannot see function names there directly, they must be parsed from `operationId` by stripping the version number. They would be available from https://apisandbox.openbankproject.com/obp/v1.4.0/resource-docs/v3.0.0/obp?core=&psd2=&obwg= (`implemented_by.function`), though.

Should API Tester rather look at the Resource Docs JSON?

**Comment by sebtesobe** [comment]
Another reason why API Tester currenctly cannot use Swagger JSON is insufficient parameter definitions. See this call to update the account label for example:

```json
"/banks/{BANK_ID}/accounts/{ACCOUNT_ID}": {

    "post": {
        "tags": [
            "1_2_1"
        ],
        "summary": "Update Account Label.",
        "security": [
            {
                "directLogin": [ ]
            }
        ],
        "description": "<p>Update the label for the account. The label is how the account is known to the account owner e.g. 'My savings account' </p>",
        "operationId": "v1_2_1-updateAccountLabel",
        "parameters": [
            {
                "in": "body",
                "name": "body",
                "description": "BANK_BODY",
                "required": true,
                "schema": {
                    "$ref": "#/definitions/UpdateAccountJSON"
                }
            },
            {
                "in": "path",
                "name": "ACCOUNT_ID",
                "description": "The account id",
                "required": true,
                "type": "string"
            },
            {
                "in": "path",
                "name": "BANK_ID",
                "description": "The bank id",
                "required": true,
                "type": "string"
            }
        ],
        "responses": {
            "201": {
                "description": "Success",
                "schema": {
                    "$ref": "#/definitions/SuccessMessage"
                }
            },
            "400": {
                "description": "Error",
                "schema": {
                    "$ref": "#/definitions/ErrorInvalidJsonFormat"
                }
            }
        }
    },
...
```

The parameters are supposed to be `id`, `label`, `bank_id` but none of those exact strings is found in the parameter section above. 

Using Resource Docs JSON, the API Tester would have to look at `example_request_body` which is rather indirect to retrieve the required parameter names, so not ideal either.

**Comment by simonredfern** [comment]
Can API Tester use both Swagger and Resource Docs? is there a key between them you can somehow use? Of course if there is data missing from Swagger, that will be gradually improved.

**Comment by sebtesobe** [comment]
I strongly advise against mixing info from Swagger and Resource Docs. They might contradict each other or just create inconsistencies. Since we have full control over them, we should fix it.

How will the gradual improvement of Swagger come about? Shall i create some tickets? There is a few regarding Swagger already and i just created a label to group them: 
https://github.com/OpenBankProject/OBP-API/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aswagger

To me it looks like everything API Tester needs atm is to be found in the Resource Docs.
