### ISSUE TITLE
Test configuration needs COUNTERPARTY_ID

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/API-Tester#8]
The current model of test configuration does not support `COUNTERPARTY_ID` as required by the call `getCounterpartyById`. This needs to be added.

**Comment by sebtesobe** [comment]
@hongwei1 Please verify

**Comment by sebtesobe** [comment]
@hongwei1 Please verify the issue was fixed

**Comment by hongwei1** [comment]
It works well.
